// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI4u9gKpXhz3VhHFASyO5VgzMgbGXCAHA',
    appId: '1:304650348761:web:7651f0b5a1b47cfd10f6c8',
    messagingSenderId: '304650348761',
    projectId: 'noteit-328eb',
    authDomain: 'noteit-328eb.firebaseapp.com',
    storageBucket: 'noteit-328eb.appspot.com',
    measurementId: 'G-P5ZZ2Y2DCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhBbs1p6pjB4KigaZGB_siXlDaW-QDSGM',
    appId: '1:304650348761:android:740bfdb85cae684910f6c8',
    messagingSenderId: '304650348761',
    projectId: 'noteit-328eb',
    storageBucket: 'noteit-328eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCanOrousLzhvT1y5CNTOuzheiERC13ftk',
    appId: '1:304650348761:ios:a008c277fc859c1710f6c8',
    messagingSenderId: '304650348761',
    projectId: 'noteit-328eb',
    storageBucket: 'noteit-328eb.appspot.com',
    iosBundleId: 'com.noteit.noteit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCanOrousLzhvT1y5CNTOuzheiERC13ftk',
    appId: '1:304650348761:ios:0f8a7b656866aec010f6c8',
    messagingSenderId: '304650348761',
    projectId: 'noteit-328eb',
    storageBucket: 'noteit-328eb.appspot.com',
    iosBundleId: 'com.noteit.noteit.RunnerTests',
  );
}
